
---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - common

- hosts: srv1
  become: true
  gather_facts: yes
  roles:
    - openldap-server

- hosts: all
  become: true
  gather_facts: yes
  roles:
    - openldap-client