---
- name: Disable dhcpclient modify resolve.conf for eth0
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0
              regexp='^PEERDNS=no'
              insertafter=EOF
              line='PEERDNS=no'
  notify:
  - restart network
  tags: networking

- name: Create resolver.conf
  
  template: src=resolv.j2 dest=/etc/resolv.conf 
  notify:
  - restart network
  become: true
  tags:
  - resolver
- meta: flush_handlers