---
- name: Install named (bind and bind-utils)
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bind
  - bind-utils
  - policycoreutils-python
  tags:
  - named

- name: Enable named
  become: true
  systemd: name=named state=started enabled=yes
  tags:
  - named

- name: Create zone dir
  become: true
  file: 
    path: /etc/named/zones/
    state: directory
    owner: named
    group: named
    mode: 0755
  tags:
  - named
  
- name: Create named configs
  become: true
  template: src={{ item.j2 }} dest={{ item.dst }} mode=0664 owner=named group=named
  notify:
  - restart named
  with_items:
  - {j2: "templates/named.conf.j2", dst: "/etc/named.conf"}
  - {j2: "templates/named.conf.local.j2", dst: "/etc/named/named.conf.local"}
  - {j2: "templates/primary.zone.j2", dst: "/etc/named/zones/primary.zone"}
  - {j2: "templates/reverse.zone.j2", dst: "/etc/named/zones/reverse.zone"}
  tags:
  - named

