- name: Disable Zero Configuration Network
  become: true
  lineinfile: dest=/etc/sysconfig/network
              regexp=''
              insertafter=EOF
              line='NOZEROCONF=yes'
  notify:
  - restart network
  tags: networking

- name: Disable NetworkManager
  become: true
  systemd: name=NetworkManager state=stopped enabled=no
  tags: networking
  
- name: Disable Firewalld
  become: true
  systemd: name=firewalld state=stopped enabled=no
  register: result
  tags: networking

- name: Check if EPEL exists
  stat: path={{ epel.repo_file }}
  register: epel_result
  tags: epel

- name: Install EPEL 
  yum:
    name: "{{ epel.url_repo }}"
    state: present
  register: result
  when: not epel_result.stat.exists
  tags: epel

- name: Import EPEL GPG
  rpm_key:
    key: "{{ epel.url_key }}"
    state: present
  when: not epel_result.stat.exists
  tags: epel
